### PR TITLE
Simplify the topiary script by moving most arg-guided logic into the package

### PR DESCRIPTION
**Pull request by iskandr**
* Renamed `args` to `commandline_args`
* Copied `.gitignore` file from PyEnsembl
* Moved all the logic of actually running Topiary out of `scripts/topiary` into a module called `predict_epitopes`.
* `predict_epitopes` has two functions: `predict_epitopes` which does the actual work, and a "unwrapping" helper called `predict_epitopes_from_args`.

[Review on Reviewable](https://reviewable.io/reviews/hammerlab/topiary/22)

### CODE REVIEW

**Comment by tavinathanson** [comment]
Looks solid to me! Just a few minor comments.

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[scripts/topiary, line 54 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa2AWT3lWVel6kZkrk)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/scripts/topiary#L54)):</sup>
Curious how this compares, in general, with `df.head(10)`?

---

<sup>**[scripts/topiary, line 69 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa3XrlszK9OB1ddX7C)** ([raw file](https://github.com/hammerlab/topiary/blob/58a37639b74840e35b92e20c4c06d9b457ff9620/scripts/topiary#L69)):</sup>
So where did this particular logic go? Don't see these few lines moved anywhere?

---

<sup>**[topiary/commandline_args.py, line 258 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa31iJYcrVgLXUDThM)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/topiary/commandline_args.py#L258)):</sup>
What about providing a Python user the ability to generate `rna_gene_expression_dict` from an FPKM file, etc.? (Versus just on the commandline)

---

<sup>**[topiary/commandline_args.py, line 287 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa2cyT8Xt9IQT0ZYg9)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/topiary/commandline_args.py#L287)):</sup>
Nit that you can totally ignore: maybe simplify code into `return load_cufflinks_fpkm_dict(args.rna_transcript_fpkm_file) if args.rna_transcript_fpkm_file else None`?

---

<sup>**[topiary/predict_epitopes.py, line 78 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa2TyB6i2_ch1ObgyY)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/topiary/predict_epitopes.py#L78)):</sup>
Comment explaining what `args` is?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/topiary/22)

**Comment by iskandr** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[scripts/topiary, line 54 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa2AWT3lWVel6kZkrk)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/scripts/topiary#L54)):</sup>
I'll use head instead, since `.ix` assumes the index is 0..n-1 (which is true in this situation but might be confusing)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/topiary/22)

**Comment by iskandr** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[topiary/commandline_args.py, line 258 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa31iJYcrVgLXUDThM)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/topiary/commandline_args.py#L258)):</sup>
Good idea, I'll add another helper, those "_from_args" functions should only do unwrapping of parameters and call something else. 

---

<sup>**[topiary/commandline_args.py, line 287 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa2cyT8Xt9IQT0ZYg9)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/topiary/commandline_args.py#L287)):</sup>
I think it's a little clearer split over multiple lines.

---

<sup>**[topiary/predict_epitopes.py, line 78 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa2TyB6i2_ch1ObgyY)** ([raw file](https://github.com/hammerlab/topiary/blob/0b9da91b19accbadadd93411d0017c15dc968ca7/topiary/predict_epitopes.py#L78)):</sup>
Good idea

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/topiary/22)

**Comment by iskandr** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[scripts/topiary, line 69 \[r1\]](https://reviewable.io:443/reviews/hammerlab/topiary/22#-Jxa3XrlszK9OB1ddX7C)** ([raw file](https://github.com/hammerlab/topiary/blob/58a37639b74840e35b92e20c4c06d9b457ff9620/scripts/topiary#L69)):</sup>
It does the same thing as calling load_cuffllinks_dict, so I got rid of it. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/topiary/22)

**Comment by tavinathanson** [comment]
Merge away :+1: (maybe after you make the `rna_gene_expression_dict_from_args` change?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/hammerlab/topiary/22)

**Pull request merged**
